apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
  name: trident
provisioner: netapp.io/trident
parameters:
  backendType: "ontap-nas"
