apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    ibm.io/provisioning-status: complete
    pv.kubernetes.io/bind-completed: "yes"
    pv.kubernetes.io/bound-by-controller: "yes"
    volume.beta.kubernetes.io/storage-provisioner: ibm.io/ibmc-block
  finalizers:
  - kubernetes.io/pvc-protection
  labels:
    app: icp-mongodb
    region: us-east
    release: mongodb
    zone: wdc07
  name: mongodbdir-icp-mongodb-0
  namespace: kube-system
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: ibmc-block-bronze
