cloudAdministratorUsername: "admin"
cloudIntegrationPlatformEndpoint: "*"
cloudIntegrationPlatformNamespace: "integration"
productionDeployment: true

global:
  registry: "docker-registry.default.svc:5000/apic"
  registrySecret: "deployer-dockercfg-prc4l"
  createCrds: true
  storageClass: ibmc-block-gold
  mode: "dev"
  routingType: route
  certSecret: ""
  extraValuesConfig: ""

# apiconnect-operator
operator:
  arch: amd64
  registry: ""
  image: "apiconnect-operator"
  tag: 2019-09-17-15-15-59-ea366f01215e13fcd1acd1b81e5006cb32483c3d
  pullPolicy: IfNotPresent
  helmTlsSecret: apic-ent-helm-tls
  serviceAccount:
    create: true
    name:
  tiller:
    useNodePort: false
    nodePort: 31514

# management subsystem
management:
  enabled: true
  certSecret: ""
  storageClass: ""
  platformApiEndpoint: mgmt.icp-proxy.patrocinio6-fa9ee67c9ab6a7791435450358e564cc-0001.us-east.containers.appdomain.cloud
  consumerApiEndpoint: mgmt.icp-proxy.patrocinio6-fa9ee67c9ab6a7791435450358e564cc-0001.us-east.containers.appdomain.cloud
  cloudAdminUiEndpoint: mgmt.icp-proxy.patrocinio6-fa9ee67c9ab6a7791435450358e564cc-0001.us-east.containers.appdomain.cloud
  apiManagerUiEndpoint: mgmt.icp-proxy.patrocinio6-fa9ee67c9ab6a7791435450358e564cc-0001.us-east.containers.appdomain.cloud
cassandra:
  cassandraClusterSize: 1
  cassandraMaxMemoryGb: 9
  cassandraVolumeSizeGb: 50
cassandraBackup:
  cassandraBackupAuthUser: ""
  cassandraBackupAuthPass: ""
  cassandraBackupHost: ""
  cassandraBackupPath: /backups
  cassandraBackupPort: 22
  cassandraBackupProtocol: sftp
  cassandraBackupSchedule: 0 0 * * *
cassandraPostmortems:
  cassandraPostmortemsAuthUser: ""
  cassandraPostmortemsAuthPass: ""
  cassandraPostmortemsHost: ""
  cassandraPostmortemsPath: /cassandra-postmortems
  cassandraPostmortemsPort: 22
  cassandraPostmortemsSchedule: 0 0 * * *

# portal subsystem
portal:
  enabled: true
  certSecret: ""
  storageClass: ""
  portalDirectorEndpoint: padmin.icp-proxy.patrocinio6-fa9ee67c9ab6a7791435450358e564cc-0001.us-east.containers.appdomain.cloud
  portalWebEndpoint: portal-web.icp-proxy.patrocinio6-fa9ee67c9ab6a7791435450358e564cc-0001.us-east.containers.appdomain.cloud
  adminStorageSizeGb: 1
  backupStorageSizeGb: 5
  dbLogsStorageSizeGb: 2
  dbStorageSizeGb: 12
  wwwStorageSizeGb: 5

portalBackup:
  siteBackupAuthUser: ""
  siteBackupAuthPass: ""
  siteBackupHost: ""
  siteBackupPath: /backups
  siteBackupPort: 22
  siteBackupProtocol: sftp
  siteBackupSchedule: 0 2 * * *

# analytics subsystem
analytics:
  enabled: true
  certSecret: ""
  storageClass: ""
  esStorageClass: ""
  enableMessageQueue: false
  mqStorageClass: ""
  analyticsIngestionEndpoint: ai.mgmt.icp-proxy.patrocinio6-fa9ee67c9ab6a7791435450358e564cc-0001.us-east.containers.appdomain.cloud
  analyticsClientEndpoint: ac.icp-proxy.patrocinio6-fa9ee67c9ab6a7791435450358e564cc-0001.us-east.containers.appdomain.cloud
  coordinatingMaxMemoryGb: 12
  dataMaxMemoryGb: 12
  dataStorageSizeGb: 200
  masterMaxMemoryGb: 12
  masterStorageSizeGb: 5

# gateway subsystem
gateway:
  enabled: true
  certSecret: ""
  storageClass: ""
  apiGatewayEndpoint: "api-gateway.icp-proxy.patrocinio6-fa9ee67c9ab6a7791435450358e564cc-0001.us-east.containers.appdomain.cloud"
  gatewayServiceEndpoint: "gwd.icp-proxy.patrocinio6-fa9ee67c9ab6a7791435450358e564cc-0001.us-east.containers.appdomain.cloud"
  replicaCount: 3
  maxCpu: 4
  maxMemoryGb: 6
  v5CompatibilityMode: true
  enableTms: false
  tmsPeeringStorageSizeGb: 10
  highPerformancePeering: off
  image: "datapower-api-gateway"
  imageTag: 2018.4.1.7-od-tracing-rel4-313058-od-tracing-rel4-release-prod
  monitoringImage: "k8s-datapower-monitor"
  monitoringImageTag: 2018.4.1-16-37918a2
  odTracing:
    enabled: false
    odManagerNamespace: "tracing"
    odAgentImage: "icp4i-od-agent"
    odAgentImageTag: "1.0.0"
    odCollectorImage: "icp4i-od-collector"
    odCollectorImageTag: "1.0.0"
  imagePullPolicy: IfNotPresent
