apiVersion: v1
kind: PersistentVolume
metadata:
  name: cmis-logstore-pv
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 1Gi
  nfs:
    path: /auto2
    server: 52.116.20.100
  persistentVolumeReclaimPolicy: Retain
  storageClassName: cmis-logstore-pv
