apiVersion: v1
kind: PersistentVolume
metadata:
  name: cmis-logstore-pv
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 1Gi
  nfs:
    path: /home/cfgstore/cmis/logs
    server: <NFS Server>
  persistentVolumeReclaimPolicy: Retain
  storageClassName: cmis-logstore-pv
