apiVersion: v1
kind: PersistentVolume
metadata:
  name: cmis-cfgstore-pv
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 1Gi
  nfs:
    path: /auto1
    server: 52.116.20.100
  persistentVolumeReclaimPolicy: Retain
  storageClassName: cmis-cfgstore-pv
