apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cmis-cfgstore-pvc
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  volumeName: cmis-cfgstore-pv
  storageClassName: cmis-cfgstore-pv
