apiVersion: v1
kind: PersistentVolume
metadata:
  name: cpelogstore-pv
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 1Gi
  nfs:
    path: /auto7
    server: 52.116.20.102
  persistentVolumeReclaimPolicy: Retain
  storageClassName: cpelogstore-pv
