apiVersion: v1
kind: PersistentVolume
metadata:
  name: cpe-filestore-pv
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 1Gi
  nfs:
    path: /auto5
    server: 52.116.20.100
  persistentVolumeReclaimPolicy: Retain
  storageClassName: cpe-filestore-pv
