apiVersion: v1
kind: PersistentVolume
metadata:
  name: cpecfgstore-pv
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 1Gi
  nfs:
    path: /auto4
    server: 52.116.20.102
  persistentVolumeReclaimPolicy: Retain
  storageClassName: cpecfgstore-pv
