apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cpecfgstore-pvc
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  volumeName: cpecfgstore-pv
  storageClassName: cpecfgstore-pv
