apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cpe-logstore-pvc
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  volumeName: cpe-logstore-pv
  storageClassName: cpe-logstore-pv
