apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cpelogstore-pvc
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  volumeName: cpelogstore-pv
  storageClassName: cpelogstore-pv
