apiVersion: v1
kind: PersistentVolume
metadata:
  name: cpe-textext-pv
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 1Gi
  nfs:
    path: /home/cfgstore/cpe/textext
    server: <NFS Server>
  persistentVolumeReclaimPolicy: Retain
  storageClassName: cpe-textext-pv
