apiVersion: v1
kind: PersistentVolume
metadata:
  name: cpetextext-pv
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 1Gi
  nfs:
    path: /auto8
    server: 52.116.20.102
  persistentVolumeReclaimPolicy: Retain
  storageClassName: cpetextext-pv
