apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cpetextext-pvc
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  volumeName: cpetextext-pv
  storageClassName: cpetextext-pv
