apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cpe-cfgstore-pvc
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  volumeName: cpe-cfgstore-pv
  storageClassName: cpe-cfgstore-pv
