apiVersion: v1
kind: PersistentVolume
metadata:
  name: cpe-cfgstore-pv
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 1Gi
  nfs:
    path: /auto4
    server: 52.116.20.100
  persistentVolumeReclaimPolicy: Retain
  storageClassName: cpe-cfgstore-pv
