apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cpe-icmrules-pvc
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  volumeName: cpe-icmrules-pv
  storageClassName: cpe-icmrules-pv
