apiVersion: v1
kind: PersistentVolume
metadata:
  name: cpefilestore-pv
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 1Gi
  nfs:
    path: /auto5
    server: 52.116.20.102
  persistentVolumeReclaimPolicy: Retain
  storageClassName: cpefilestore-pv
