apiVersion: v1
kind: PersistentVolume
metadata:
  name: cpe-icmrules-pv
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 1Gi
  nfs:
    path: /auto6
    server: 52.116.20.102
  persistentVolumeReclaimPolicy: Retain
  storageClassName: cpe-icmrules-pv
