apiVersion: v1
kind: PersistentVolume
metadata:
  name: cpefnlogstore-pv
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 1Gi
  nfs:
    path: /auto16
    server: 52.116.20.102
  persistentVolumeReclaimPolicy: Retain
  storageClassName: cpefnlogstore-pv
