apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cpefnlogstore-pvc
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  volumeName: cpefnlogstore-pv
  storageClassName: cpefnlogstore-pv
