apiVersion: v1
kind: PersistentVolume
metadata:
  name: cpeicmrulesstore-pv
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 1Gi
  nfs:
    path: /auto14
    server: 52.116.20.102
  persistentVolumeReclaimPolicy: Retain
  storageClassName: cpeicmrulesstore-pv
