apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cpeicmrulesstore-pvc
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  volumeName: cpeicmrulesstore-pv
  storageClassName: cpeicmrulesstore-pv
