apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cpetextextstore-pvc
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  volumeName: cpetextextstore-pv
  storageClassName: cpetextextstore-pv
