apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: css-indexstore-pvc
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  volumeName: css-indexstore-pv
  storageClassName: css-indexstore-pv
