apiVersion: v1
kind: PersistentVolume
metadata:
  name: css-cfgstore-pv
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 1Gi
  nfs:
    path: /home/cfgstore/css/CSS_Server_data
    server: <NFS_SERVER>
  persistentVolumeReclaimPolicy: Retain
  storageClassName: css-cfgstore-pv
