apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: css-icp-customstore-pvc
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  volumeName: css-icp-customstore-pv
  storageClassName: css-icp-customstore
