apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: css-logstore-pvc
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  volumeName: css-logstore-pv
  storageClassName: css-logstore-pv
