apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: css-cfgstore-pvc
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  volumeName: css-cfgstore-pv
  storageClassName: css-cfgstore-pv
